#ManagedBy: cue

metadata:
  name: karpenter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::319951235442:role/karpenter
    eks.amazonaws.com/audience: sts.amazonaws.com
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/token-expiration: "86400"
kind: ServiceAccount
apiVersion: v1
