helmCharts:
- includeCRDs: true
  name: any-resource
  releaseName: bootstrap
  repo: https://kiwigrid.github.io
  valuesInline:
    anyResources:
      argo-cd: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-argo-cd
          annotations:
            argocd.argoproj.io/sync-wave: "1000"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/argo-cd
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      caddy: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-caddy
          annotations:
            argocd.argoproj.io/sync-wave: "50"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/caddy
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      cert-manager: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-cert-manager
          annotations:
            argocd.argoproj.io/sync-wave: "2"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/cert-manager
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      defn: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-defn
          annotations:
            argocd.argoproj.io/sync-wave: "31"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/defn
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      defn-shared: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-defn-shared
          annotations:
            argocd.argoproj.io/sync-wave: "30"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/defn-shared
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      external-secrets-operator: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-external-secrets-operator
          annotations:
            argocd.argoproj.io/sync-wave: "10"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/external-secrets-operator
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      k3d-global-secrets-store: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-secrets-store
          annotations:
            argocd.argoproj.io/sync-wave: "20"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/k3d-global-secrets-store
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      knative: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-knative
          annotations:
            argocd.argoproj.io/sync-wave: "30"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/knative
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      kourier: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-kourier
          annotations:
            argocd.argoproj.io/sync-wave: "30"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/kourier
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      kyverno: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-kyverno
          annotations:
            argocd.argoproj.io/sync-wave: "1"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/kyverno
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - ServerSideApply=true
      pod-identity-webhook: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-pod-identity-webhook
          annotations:
            argocd.argoproj.io/sync-wave: "10"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/pod-identity-webhook
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
      tfo: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          namespace: argocd
          name: k3d-global-tfo
          annotations:
            argocd.argoproj.io/sync-wave: "30"
        spec:
          project: default
          destination:
            name: k3d-global
          source:
            repoURL: https://github.com/defn/app
            targetRevision: master
            path: k/tfo
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: []
  version: 0.1.0
