apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: k3d-global-cert-manager
  namespace: argocd
spec:
  destination:
    name: k3d-global
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/cert-manager
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-global-external-secrets-operator
  namespace: argocd
spec:
  destination:
    name: k3d-global
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/external-secrets-operator
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  name: k3d-global-kuma-global
  namespace: argocd
spec:
  destination:
    name: k3d-global
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/k3d-global-kuma-global
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-global-kyverno
  namespace: argocd
spec:
  destination:
    name: k3d-global
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/kyverno
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: k3d-global-mesh
  namespace: argocd
spec:
  destination:
    name: k3d-global
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/mesh
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-global-pod-identity-webhook
  namespace: argocd
spec:
  destination:
    name: k3d-global
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/pod-identity-webhook
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: k3d-global-secrets-store
  namespace: argocd
spec:
  destination:
    name: k3d-global
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/k3d-global-secrets-store
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  name: k3d-global-tfo
  namespace: argocd
spec:
  destination:
    name: k3d-global
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/tfo
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
