apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dev
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: k3d-smiley
          role: external-secrets
      path: kv
      server: http://100.103.25.109:8200
      version: v2
