helmCharts:
- includeCRDs: true
  name: kyverno
  namespace: kyverno
  releaseName: kyverno
  repo: https://kyverno.github.io/kyverno
  valuesInline:
    replicaCount: 1
  version: 2.5.5
namespace: kyverno
resources:
- resource-namespace-kyverno.yaml
