helmCharts:
- includeCRDs: true
  name: caddy
  namespace: caddy
  releaseName: caddy
  repo: https://charts.alekc.dev
  version: 0.2.4
namespace: caddy
patches:
- path: patch-service-tailscale.yaml
resources:
- resource-namespace-caddy.yaml
