#ManagedBy: cue

patches:
  - path: patch-service-tailscale.yaml
namespace: caddy
resources:
  - resource-namespace-caddy.yaml
helmCharts:
  - releaseName: caddy
    namespace: caddy
    valuesInline:
      https:
        enabled: true
        port: 443
      config:
        caddyFile: |-
          :80 {
            handle / {
             respond "hello1"
            }
          }

          :443 {
            handle / {
             respond "hello2"
            }
          }
    name: caddy
    version: 0.2.4
    repo: https://charts.alekc.dev
    includeCRDs: true
