#ManagedBy: cue

patches:
  - path: patch-service-tailscale.yaml
namespace: caddy
resources:
  - resource-namespace-caddy.yaml
helmCharts:
  - releaseName: caddy
    namespace: caddy
    valuesInline:
      listenPort: 80
      https:
        enabled: true
        port: 443
      config:
        caddyFile: |-
          https://argocd.defn.run {
          	reverse_proxy https://argocd-server.argocd.svc.cluster.local {
          		transport http {
          			tls
          			tls_insecure_skip_verify
          		}
          	}
          }
        global: |-
          log {
          	local_certs
          	output stdout
          }
    name: caddy
    version: 0.2.4
    repo: https://charts.alekc.dev
    includeCRDs: true
