namespace: karpenter
resources:
- karpenter.yaml
- resource-namespace-karpenter.yaml
- resource-provisioner-control-vc1.yaml
- resource-provisioner-control-vc2.yaml
- resource-provisioner-control-vc3.yaml
- resource-provisioner-control-vc4.yaml
