#ManagedBy: cue

metadata:
  name: domainmapping-webhook
  namespace: knative-serving
spec:
  template:
    metadata:
      annotations:
        traffic.kuma.io/exclude-inbound-ports: "8443"
        kuma.io/virtual-probes: disabled
kind: Deployment
apiVersion: apps/v1
