#ManagedBy: cue

metadata:
  name: domain-mapping
  namespace: knative-serving
spec:
  template:
    metadata:
      annotations:
        kuma.io/virtual-probes: disabled
kind: Deployment
apiVersion: apps/v1
