#ManagedBy: cue

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dev
  target:
    name: dev
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dev/amanibhavam-global
