apiVersion: v1
kind: Service
metadata:
  name: {{ include "caddy.fullname" . }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.listenPort }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.https.enabled }}
    - name: https
      targetPort: https
      protocol: TCP
      port: {{ .Values.https.port }}
  {{- end }}
  selector:
    {{- include "caddy.selectorLabels" . | nindent 4 }}
