helmCharts:
- includeCRDs: true
  name: vcluster
  namespace: control-vc4
  releaseName: vcluster
  repo: https://charts.loft.sh
  valuesInline:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: In
              values:
              - control-vc4
    service:
      type: ClusterIP
    sync:
      nodes:
        enabled: true
        nodeSelector: env=control-vc4
    syncer:
      extraArgs:
      - --tls-san=vcluster.control-vc4.svc.cluster.local
      - --enforce-toleration=env=control-vc4:NoSchedule
    tolerations:
    - key: env
      operator: Equal
      value: control-vc4
    vcluster:
      image: rancher/k3s:v1.24.12-k3s1
  version: 0.14.2
namespace: control-vc4
resources:
- resource-namespace-vcluster.yaml
