#ManagedBy: cue

patchesStrategicMerge: []
resources: []
helmCharts:
  - releaseName: bootstrap
    valuesInline:
      anyResources:
        cert-manager: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-cert-manager
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/cert-manager
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        pod-identity-webhook: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-pod-identity-webhook
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/pod-identity-webhook
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        external-secrets-operator: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-external-secrets-operator
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/external-secrets-operator
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        k3d-control-secrets-store: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-secrets-store
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/k3d-control-secrets-store
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        tfo: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-tfo
            annotations:
              argocd.argoproj.io/sync-wave: "30"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/tfo
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        knative: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-knative
            annotations:
              argocd.argoproj.io/sync-wave: "30"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/knative
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        kourier: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-kourier
            annotations:
              argocd.argoproj.io/sync-wave: "40"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/kourier
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        rocky: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-rocky
            annotations:
              argocd.argoproj.io/sync-wave: "50"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/rocky
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        rosie: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-rosie
            annotations:
              argocd.argoproj.io/sync-wave: "50"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/rosie
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        bonchon: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-bonchon
            annotations:
              argocd.argoproj.io/sync-wave: "50"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/bonchon
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    includeCRDs: true
