helmCharts:
- includeCRDs: true
  name: external-dns
  namespace: external-dns
  releaseName: external-dns
  repo: https://charts.bitnami.com/bitnami
  valuesInline:
    provider: cloudflare
    sources:
    - service
    - ingress
  version: 6.7.2
namespace: external-dns
resources:
- resource-namespace-external-dns.yaml
