apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: dry-brine-rocky-chicken
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - test "completed" == "$(kubectl get tf "rocky" -o json | jq -r '.status.phase')"
        command:
        - bash
        - -c
        image: defn/dev:kubectl
        name: meh
      restartPolicy: Never
      serviceAccountName: default
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: dry-brine-rosie-chicken
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - test "completed" == "$(kubectl get tf "rosie" -o json | jq -r '.status.phase')"
        command:
        - bash
        - -c
        image: defn/dev:kubectl
        name: meh
      restartPolicy: Never
      serviceAccountName: default
---
apiVersion: tf.isaaguilar.com/v1alpha2
kind: Terraform
metadata:
  name: bonchon
  namespace: default
spec:
  backend: "terraform {\n\tbackend \"kubernetes\" {\n\t\tin_cluster_config = true\n\t\tsecret_suffix
    \    = \"bonchon\"\n\t\tnamespace         = \"default\"\n\t}\n}"
  ignoreDelete: true
  keepLatestPodsOnly: true
  outputsToOmit:
  - "0"
  scmAuthMethods: []
  serviceAccount: default
  terraformModule:
    source: https://github.com/defn/app.git//tf/m/fried-chicken?ref=master
  terraformVersion: 1.0.0
