#ManagedBy: cue

patches: []
namespace: external-dns
resources:
  - resource-namespace-external-dns.yaml
helmCharts:
  - releaseName: external-dns
    namespace: external-dns
    valuesInline:
      sources:
        - service
        - ingress
      provider: cloudflare
    name: external-dns
    version: 6.7.2
    repo: https://charts.bitnami.com/bitnami
    includeCRDs: true
