#ManagedBy: cue

apiVersion: tf.isaaguilar.com/v1alpha2
kind: Terraform
metadata:
  name: rosie
  namespace: default
spec:
  terraformVersion: 1.0.0
  terraformModule:
    source: https://github.com/defn/app.git//tf/m/chicken?ref=master
  taskOptions:
    - for:
        - '*'
      env:
        - name: TF_VAR_chicken
          value: rosie
  serviceAccount: default
  scmAuthMethods: []
  ignoreDelete: true
  keepLatestPodsOnly: true
  outputsToOmit:
    - "0"
  backend: |-
    terraform {
      backend "kubernetes" {
        in_cluster_config = true
        secret_suffix     = "rosie"
        namespace         = "default"
      }
    }
