#ManagedBy: cue

patches: []
resources: []
helmCharts:
  - releaseName: bootstrap
    valuesInline:
      anyResources:
        cert-manager: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: vcluster-control-vc3-cert-manager
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: vcluster-control-vc3
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/cert-manager
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    includeCRDs: true
