helmCharts:
- includeCRDs: true
  name: kuma
  namespace: kuma
  releaseName: kuma
  repo: https://kumahq.github.io/charts
  valuesInline:
    controlPlane:
      kdsGlobalAddress: grpcs://100.64.110.16:5685
      mode: zone
      tls:
        general:
          caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhRENDQWxDZ0F3SUJBZ0lRVmFrY1RoQ2lEb3oyYVdVRXhDVk1jVEFOQmdrcWhraUc5dzBCQVFzRkFEQWkKTVNBd0hnWURWUVFERXhkcmRXMWhMV052Ym5SeWIyd3RjR3hoYm1VdWEzVnRZVEFlRncweU1qRXdNVE13TXpNMApNVEZhRncwek1qRXdNVEF3TXpNME1URmFNQ0l4SURBZUJnTlZCQU1URjJ0MWJXRXRZMjl1ZEhKdmJDMXdiR0Z1ClpTNXJkVzFoTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxeEozN093L2NRRlYKQldQcTNOTUd6OGNvdjFlT0pOcVo1K0hudXZlSVdlQ0NjOWNQR2FIMzlBRkRNUVA3Q0FiT3drVzAzemZ4YnVnUQprSnF3RXpQd2FBK1FHdkdPK09FRVNENUJyeSthNEFyV0ZoZVFhOTZCdUhoN0pyUHVoczFJRnVwakFxc0M3dEtOCkQwczllNnA1Ry9GeTFmcXJ2RVlWWUxqaTIyTGp4d0tnb0ZHWm1yWXZ1MFcvK3FJNUM1OGF4R1Iwa21OUUI5VE0KTGU4K3V5ZmNoVnI2a2Iyb0ZHWUpneFNORjh6ZWxVWmJRbmlCWUFsU1dXWEVMZ21YaHVhNzl6ZkhkaVJQbWVqVgpoNktheWJWR3RrSEFBREdXY0tSdkpOMlhORDBqaTZmbDZQUGVJRjNianZ2SXFkTWhvckN2NjV1TUt4Q0lUSHp0Cjg1OXJ6R0JMOVFJREFRQUJvNEdaTUlHV01BNEdBMVVkRHdFQi93UUVBd0lDcERBVEJnTlZIU1VFRERBS0JnZ3IKQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlRvZVc0VTFDcVRSbGtGTHNDdApKK2ZrQXdiRUZqQS9CZ05WSFJFRU9EQTJnaGRyZFcxaExXTnZiblJ5YjJ3dGNHeGhibVV1YTNWdFlZSWJhM1Z0CllTMWpiMjUwY205c0xYQnNZVzVsTG10MWJXRXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBLzl3YWEKWVpucTJQaTBmUk1Ma00velNHaDMwcys0OWZITW5JUWtGRVRiNisvZmNCazB6S2J6U3NGRy9obFB4YWdzRXdRTQpCcFZtUnNMV21YUVBzUUR3bUx4TnJDQ1g4NXFsLzJYdVJSdys2RmN3MzRhK252Y0VXWVpQUUJhUU83UGtSOVFCCmpPeGRqUGp3cVVSWWowTURVSVVkMVB6MzJJUTE5b3d6MHJieGtpRWxrNk1EOGlCMXFva3pzb0E3di9WR1Y4RGQKQU41NVNHM3hTbHE1bnFPU2N3NENMa2lGUmt2MnZDbUZnQ2phME05clJIMlR4U2lkNHRIOE96QkZlT09OL0hCRgpSb2ZTZmdvV21mbDUreDJ2K2Fpd2drK0d2WVY3ZHVBYkVkaFVOMFNRZDNkc282ZktaMUdIQ2tYbmhUMVFreDZoCmhRazlkcnFJczc1Umw3VUIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
          secretName: kuma-tls-cert
        kdsZoneClient:
          secretName: kds-ca-certs
      zone: k3d-smiley
    egress:
      enabled: true
    ingress:
      enabled: true
  version: 1.8.1
namespace: kuma
resources:
- resource-namespace-kuma.yaml
- resource-external-secret-kds-ca-certs.yaml
- resource-external-secret-kuma-tls-cert.yaml
