apiVersion: v1
kind: Namespace
metadata:
  labels:
    kuma.io/mesh: dev
    kuma.io/sidecar-injection: disabled
  name: default
  namespace: default
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    networking.knative.dev/ingress.class: kong
  labels:
    networking.knative.dev/visibility: cluster-local
  name: bye
  namespace: default
spec:
  template:
    metadata:
      annotations:
        kuma.io/mesh: dev
        kuma.io/sidecar-injection: enabled
        kuma.io/virtual-probes: disabled
        traffic.kuma.io/exclude-inbound-ports: "8012"
    spec:
      containerConcurrency: 0
      containers:
      - image: containous/whoami:latest
        name: whoami
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    networking.knative.dev/ingress.class: kong
  labels:
    networking.knative.dev/visibility: cluster-local
  name: hello
  namespace: default
spec:
  template:
    metadata:
      annotations:
        kuma.io/mesh: dev
        kuma.io/sidecar-injection: enabled
        kuma.io/virtual-probes: disabled
        traffic.kuma.io/exclude-inbound-ports: "8012"
    spec:
      containerConcurrency: 0
      containers:
      - image: containous/whoami:latest
        name: whoami
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100
