#ManagedBy: cue

patches:
  - path: patch-configmap-argocd-cm.yaml
namespace: argocd
resources:
  - resource-namespace-argocd.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/install.yaml
