#ManagedBy: cue

patchesStrategicMerge:
  - patch-configmap-argocd-cm.yaml
namespace: argocd
resources:
  - resource-namespace-argocd.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.4/manifests/install.yaml
