#ManagedBy: cue

patches:
  - path: patch-clusterrole-kyverno-generate.yaml
namespace: kyverno
resources:
  - resource-namespace-kyverno.yaml
helmCharts:
  - releaseName: kyverno
    namespace: kyverno
    valuesInline:
      replicaCount: 1
    name: kyverno
    version: 2.7.2
    repo: https://kyverno.github.io/kyverno
    includeCRDs: true
