#ManagedBy: cue

patches: []
namespace: kyverno
resources:
  - resource-namespace-kyverno.yaml
  - resource-clusterrole-create-clusterissuers.yaml
  - resource-clusterrole-get-secrets.yaml
helmCharts:
  - releaseName: kyverno
    namespace: kyverno
    valuesInline:
      replicaCount: 1
    name: kyverno
    version: 2.7.2
    repo: https://kyverno.github.io/kyverno
    includeCRDs: true
