#ManagedBy: cue

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:generate
rules:
  - apiGroups:
      - cert-manager.io/v1
    resources:
      - clusterissuers
    verbs:
      - create
      - update
      - patch
      - delete
