#ManagedBy: cue

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:get-secrets
  labels:
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
