apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: TODO

    privateKeySecretRef:
      name: zerossl-production

    externalAccountBinding:
      keyID: TODO
      keySecretRef:
        name: dev
        key: zerossl-eab-hmac

    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: TODO
          apiTokenSecretRef:
            name: dev
            key: cloudflare-api-token