#ManagedBy: cue

patches: []
namespace: global-vc0
resources:
  - resource-namespace-vcluster.yaml
helmCharts:
  - releaseName: vcluster
    namespace: global-vc0
    valuesInline:
      service:
        type: ClusterIP
      vcluster:
        image: rancher/k3s:v1.24.12-k3s1
      syncer:
        extraArgs:
          - --tls-san=vcluster.global-vc0.svc.cluster.local
          - --enforce-toleration=env=global-vc0:NoSchedule
      sync:
        nodes:
          enabled: true
          nodeSelector: env=global
      tolerations:
        - key: env
          value: global
          operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - global
    name: vcluster
    version: 0.14.2
    repo: https://charts.loft.sh
    includeCRDs: true
